#!/bin/bash

stable() {
	curl http://log_check.yidaip2p.net/branches_match/Log/match/algorithm-$1.log > algorithm.txt && cat algorithm.txt && rm -rf algorithm.txt
}

release() {
	curl http://logmatch.yixiaoqian.com/Log/match/algorithm-$1.log > algorithm.txt && cat algorithm.txt && rm -rf algorithm.txt
}

for arg in $@; do
	name=${arg%=*}
	value=${arg#*=}
	
	case $name in
		'--stable') stable $value;;
		'--release') release $value;;
		*) echo '查看平台日志？[--stable|--release]';;
	esac
done


